# Generated by Django 2.0.4 on 2018-04-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmlchat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
