# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dmlcomments', '0007_auto_20170222_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visitor',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
