# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmlcomments', '0008_comment_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date']},
        ),
    ]
