# Generated by Django 2.2.3 on 2019-07-23 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0002_auto_20180425_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 7, 23, 13, 40, 1, 909072, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
