# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0002_question_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
