# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0002_auto_20170220_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
