# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0004_auto_20160928_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
