# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0005_auto_20160928_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
