# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmlpolls', '0006_auto_20160928_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Author',
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
