# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmlpolls', '0009_auto_20161101_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmlpolls.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmlpolls.Question')),
            ],
        ),
    ]
