# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import dmlblog.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=dmlblog.models.upload_location, width_field='image_width'),
        ),
    ]
