# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:19
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
