# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0005_post_read_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
    ]
