# Generated by Django 2.2.3 on 2019-07-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0010_auto_20180425_1212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
