# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0011_auto_20161027_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='/'),
        ),
    ]
