# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0012_auto_20161027_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
    ]
