# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0013_post_height_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='/'),
        ),
    ]
