# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0018_auto_20161027_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='', width_field='image_width'),
        ),
    ]
