# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmlblog', '0019_auto_20161027_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=100),
        ),
    ]
